repos:
    - repo: https://github.com/ambv/black
      rev: 22.8.0
      hooks:
        - id: black

    # Sort imports
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
      - id: isort
        args: ["--profile", "black"]

    - repo: https://gitlab.com/pycqa/flake8
      rev: 5.0.4
      hooks:
      - id: flake8
        args: ['--ignore=E203,E501,F811,E712,W503']
        exclude: __init__.py

    # Formatting, Whitespace, etc
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ['--fix=no']
