_target_: transformers.TrainingArguments
output_dir: "."
learning_rate: 1e-5
gradient_checkpointing: false
gradient_accumulation_steps: 2
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-12
weight_decay: 0.00
warmup_steps: 10
eval_steps: 50
save_steps: 100
num_train_epochs: 2
logging_steps: 10
max_grad_norm: 2.0
save_total_limit: 4
fp16: false
